### ISSUE TITLE
Something about the title

### ISSUE THREAD

**Issue by samuelmolinski** [kristianmandrup/aurelia-realtime-rethinkdb-sample#1]
So the title is "Aurelia" but the description is for Angularjs which is it?  ;)

**Comment by kristianmandrup** [comment]
Ah yeah, sorry. This sample is not working. Was meant as a baseline for my `aurelia-rethinkdb` plugin, which I incidentally never got configured to work with the Aurelia configuration, since there was no documentation on writing Aurelia plugins at that time...

Check out: https://www.npmjs.com/package/aurelia-rethink-bindtable

The test cases should run and showcase that the underlying engine works. You are welcome to improve it and make the plugin work with Aurelia 1.0 :)
